language: node_js
node_js:
- '0.11'
# addons:
#   code_climate:
#     repo_token: <REPO TOKEN GOES HERE>
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: lORO2WJjxxF3WMs/d5+pXx8PU0l8HnZ+DDZFbbqYTrT/R+LOCx3Yl3lwLQUdoEzxQq2Zwyq9kVvVXq3RQ5JLsByLHPas9oeDrxOkb/oVrfln7fXjF8O/7lYyqFuDOIWzf7qeYW1ytWpmnGXRll9GEXYW7C3qGJShEOhjW2UbXJ+7AVx8B9cHujRn6++jfBPe4P3UD01YRl+cs3Ou5HlurU/GRSchdGomOMK9T2Ae5sXaf43YRT3P1GJhmJnzS9pmKGyPB02fBLtKubg5XFudTD2XqO08nHAAm4S9jE0I5tAQ2yVqfIRaPpYKTj4wOyTBFBwjBffuDfsjI5fDXnA6CtQ17F/DWAPFqbyOKvxRIXnFRcHDQerv6R910EXtPKqqMLbuM87+yy9xIpVZGuCoDxz5zIIG6b/zWFg3oAbGwyV0XldTWlev3CyFatmTfwrxmRpuv2lCWQ+eyEH3NPwV5SUJVCxhWq/cAy18rHAul09XhYLsXIYdpJJExYzLYS4+R2kJWcmlKzfR+JaO5Ajln8NyuN8fNWrYU0kx6bLYELd3uu5sJxAcr1ko2zYfmWt7LToidBmNPquSKfEbgz/FOdA9NR9OrSTNZalRN4TOLRDHK1FcUCeQ3E1KNAYWdAWSRo33xNfYjSjD7AsmO+1YyvS4doJrIgIU+uyG/J09SVY=
  on:
    tags: true
    branches: true
